services:
  db:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4.2-management # management version includes web UI
    hostname: local-rabbit # CRITICAL: Fixed hostname for data persistence
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP protocol port (for Producer/Consumer)
      - "15672:15672" # Management UI (http://localhost:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persists queues, users, and vhosts
    healthcheck:
      # Tests if the RabbitMQ management port is responding
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  producer:
    develop:
      watch:
        - path: ./producer/Dockerfile
          action: rebuild
        - path: ./producer/pyproject.toml
          action: rebuild
        - path: ./producer/poetry.lock
          action: rebuild
        # Sync source code changes instantly
        - path: ./producer
          target: /app
          action: sync
    build: ./producer
    # restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
  worker:
    develop:
      watch:
        - path: ./worker/Dockerfile
          action: rebuild
        - path: ./worker/pyproject.toml
          action: rebuild
        - path: ./worker/poetry.lock
          action: rebuild
        # Sync source code changes instantly
        - path: ./worker/src
          target: /app/src
          action: sync
    build: ./worker
    # restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on: [rabbitmq, db]
    volumes:
      - ./logs:/app/logs:z

volumes:
  postgres_data:
  rabbitmq_data:
